version: 1.0.1
workflows:
   - name: phoenix
     publish: True
     authors:
       - name: Jill Hagey
         email: qpk9@cdc.gov
         affiliation: Division of Healthcare Quality Promotion (DHQP), CDC
         orcid: 0000-0002-1308-3429
     filters:
       branches: 
         - v1.0.1